"""PDF investigation report generator."""

import os
from datetime import datetime, timezone
from pathlib import Path

from app.core.config import settings


def generate_report_pdf(case: dict, analysis: dict, officer_name: str) -> str:
    """Generate professional PDF investigation report."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    reports_dir = Path(settings.upload_dir) / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    filename = f"report_{case.get('case_id', 'unknown')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = reports_dir / filename

    doc = SimpleDocTemplate(str(filepath), pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=18, spaceAfter=12, textColor=colors.darkblue)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, spaceAfter=8, textColor=colors.darkblue)
    body_style = styles["BodyText"]
    disclaimer_style = ParagraphStyle("Disclaimer", parent=body_style, fontSize=9, textColor=colors.grey, backColor=colors.lightgrey)

    story = []

    story.append(Paragraph("INVESTIGATION REPORT", title_style))
    story.append(Paragraph(f"Case ID: {case.get('case_id', 'N/A')} | FIR: {case.get('fir_number', 'N/A')}", body_style))
    story.append(Paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("DISCLAIMER", heading_style))
    story.append(Paragraph(
        "This report is generated by AI-assisted analysis for investigative support only. "
        "It does not constitute proof of guilt. All findings require human verification and proper legal procedures.",
        disclaimer_style,
    ))
    story.append(Spacer(1, 0.2 * inch))

    sections = [
        ("Executive Summary", _executive_summary(case, analysis)),
        ("Crime Overview", _crime_overview(case)),
        ("Victim Information", _format_dict(case.get("victim_details"))),
        ("Suspect Analysis", _suspect_section(analysis)),
        ("Witness Summary", _format_dict(case.get("witness_details"))),
        ("Evidence Analysis", _evidence_section(analysis)),
        ("Timeline", _timeline_section(analysis)),
        ("Investigation Predictions", _predictions_section(analysis)),
        ("Missing Evidence", _missing_evidence(analysis)),
        ("Recommendations", _recommendations_section(analysis)),
        ("Confidence Score", f"Overall AI Confidence: {analysis.get('predictions', {}).get('confidence_score', 0.6):.0%}"),
        ("Officer Notes", case.get("additional_notes") or "None recorded."),
    ]

    for title, content in sections:
        story.append(Paragraph(title, heading_style))
        story.append(Paragraph(str(content).replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 0.15 * inch))

    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(f"Prepared by: {officer_name}", body_style))
    story.append(Paragraph("Digital Signature: [Pending Supervisor Approval]", body_style))

    doc.build(story)
    return str(filepath)


def _executive_summary(case: dict, analysis: dict) -> str:
    pred = analysis.get("predictions", {})
    return (
        f"A {case.get('crime_category', 'Unknown')} case at {case.get('location', 'unknown location')}. "
        f"Solvability estimate: {pred.get('solvability_percentage', 'N/A')}%. "
        f"Likely motive (hypothesis): {pred.get('likely_motive', 'Under investigation')}."
    )


def _crime_overview(case: dict) -> str:
    return f"Station: {case.get('police_station')}. Date: {case.get('incident_date')}. {case.get('crime_description', '')[:500]}"


def _format_dict(data) -> str:
    if not data:
        return "No data recorded."
    if isinstance(data, dict):
        return "; ".join(f"{k}: {v}" for k, v in data.items())
    return str(data)


def _suspect_section(analysis: dict) -> str:
    rankings = analysis.get("suspect_rankings", {}).get("rankings", [])
    if not rankings:
        return "No suspect analysis available."
    lines = []
    for r in rankings[:5]:
        lines.append(f"#{r['rank']} {r['suspect']} — Prob: {r['probability']:.0%}, Risk: {r['risk_level']}")
    return " | ".join(lines)


def _evidence_section(analysis: dict) -> str:
    ev = analysis.get("evidence_analysis", {})
    detected = [d["type"] for d in ev.get("detected_evidence", [])]
    return f"Detected: {', '.join(detected) or 'None'}. Strength: {ev.get('overall_strength', 0):.0%}"


def _timeline_section(analysis: dict) -> str:
    events = analysis.get("timeline", {}).get("events", [])
    return " → ".join(e["title"][:30] for e in events[:6])


def _predictions_section(analysis: dict) -> str:
    pred = analysis.get("predictions", {})
    return f"Motive: {pred.get('likely_motive')}. Complexity: {pred.get('investigation_complexity')}. Duration: {pred.get('expected_duration_days')}"


def _missing_evidence(analysis: dict) -> str:
    missing = analysis.get("evidence_analysis", {}).get("missing_evidence", [])
    return ", ".join(m["type"] for m in missing) or "None flagged"


def _recommendations_section(analysis: dict) -> str:
    recs = analysis.get("recommendations", {}).get("recommendations", [])
    return "; ".join(r["action"] for r in recs[:5])
