spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crime_analytics_dev}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

logging:
  level:
    root: INFO
    com.crime.analytics: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
